/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.lms.view;

import edu.ijse.lms.controller.BookController;
import edu.ijse.lms.dto.BookDto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class BookView extends javax.swing.JFrame {
    private final BookController BOOK_CONTROLLER;
    /**
     * Creates new form BookView
     */
    public BookView() {
        initComponents();
        this.BOOK_CONTROLLER=new BookController();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        booklable = new javax.swing.JLabel();
        booklable1 = new javax.swing.JLabel();
        booklable2 = new javax.swing.JLabel();
        booklable3 = new javax.swing.JLabel();
        booklable4 = new javax.swing.JLabel();
        codetxt = new javax.swing.JTextField();
        authortxt = new javax.swing.JTextField();
        titletxt = new javax.swing.JTextField();
        availabilitytxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        booktable = new javax.swing.JTable();
        deletebtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        categorycode = new javax.swing.JLabel();
        categorytxt = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        booklable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        booklable.setText("Book Form");

        booklable1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        booklable1.setText("Book Code");

        booklable2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        booklable2.setText("Book Title");

        booklable3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        booklable3.setText("Author");

        booklable4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        booklable4.setText("Availability");

        authortxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authortxtActionPerformed(evt);
            }
        });

        availabilitytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availabilitytxtActionPerformed(evt);
            }
        });

        booktable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        booktable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        booktable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booktableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(booktable);

        deletebtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        savebtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        updatebtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        categorycode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        categorycode.setText("Category Code");

        categorytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorytxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(booklable, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(booklable1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(booklable2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(booklable3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(titletxt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(codetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(categorycode)
                                            .addComponent(booklable4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(authortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(categorytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(availabilitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updatebtn)
                        .addGap(18, 18, 18)
                        .addComponent(deletebtn)
                        .addGap(18, 18, 18)
                        .addComponent(savebtn)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(booklable)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(booklable1)
                    .addComponent(codetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categorycode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(categorytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(booklable2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titletxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availabilitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(booklable4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(booklable3)
                    .addComponent(authortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebtn)
                    .addComponent(deletebtn)
                    .addComponent(updatebtn))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void booktableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booktableMouseClicked
        searchMouseClick();
        // TODO add your handling code here:
        //        int i=itemtable.getSelectedRow();
        //        TableModel model=itemtable.getModel();
        //        itemtextfield.setText(model.getValueAt(i, 0).toString());
        //        desctextfield.setText(model.getValueAt(i, 1).toString());
        //        packtextfield.setText(model.getValueAt(i, 2).toString());
        //        unitpricefield.setText(model.getValueAt(i, 3).toString());
        //        qtyfield.setText(model.getValueAt(i, 4).toString());
       
    }//GEN-LAST:event_booktableMouseClicked

    private void availabilitytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availabilitytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availabilitytxtActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        deleteBook();
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        saveBook();
    }//GEN-LAST:event_savebtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        updateBook();
        // TODO add your handling code here:
    }//GEN-LAST:event_updatebtnActionPerformed

    private void categorytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categorytxtActionPerformed

    private void authortxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authortxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authortxtActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BookView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BookView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BookView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BookView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new BookView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authortxt;
    private javax.swing.JTextField availabilitytxt;
    private javax.swing.JLabel booklable;
    private javax.swing.JLabel booklable1;
    private javax.swing.JLabel booklable2;
    private javax.swing.JLabel booklable3;
    private javax.swing.JLabel booklable4;
    private javax.swing.JTable booktable;
    private javax.swing.JLabel categorycode;
    private javax.swing.JTextField categorytxt;
    private javax.swing.JTextField codetxt;
    private javax.swing.JButton deletebtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField titletxt;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables

    private void saveBook(){
        try {
            BookDto bookDto=new BookDto(codetxt.getText(),titletxt.getText(),authortxt.getText(),categorytxt.getText(),Integer.parseInt(availabilitytxt.getText()));
            String resp = BOOK_CONTROLLER.saveBook(bookDto);
            JOptionPane.showMessageDialog(this, resp);
            loadTable();
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void updateBook() {
        try {
            BookDto bookDto=new BookDto(codetxt.getText(),titletxt.getText(),authortxt.getText(),categorytxt.getText(),Integer.parseInt(availabilitytxt.getText()));
             String resp = BOOK_CONTROLLER.updateBook(bookDto);
             JOptionPane.showMessageDialog(this, resp);
             loadTable();
             clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void deleteBook() {
        try {
            String bookID=codetxt.getText();
            String resp = BOOK_CONTROLLER.deleteBook(bookID);
            JOptionPane.showMessageDialog(this, resp);
            loadTable();
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void loadTable() {
        try {
             String columns[]={"BookCode","BookTitle","Author ","CategoryCode"," Availability"};
              DefaultTableModel dtm= new DefaultTableModel(columns,0){
                  @Override
                   public boolean isCellEditable(int row,int column){
                        return false;
                } 
              };  
              booktable.setModel(dtm);
              ArrayList<BookDto> bookDto=BOOK_CONTROLLER.getAll();
              for(BookDto bookdto:bookDto){
                  Object[] rowData={bookdto.getBookCode(),bookdto.getBookTitle(),bookdto.getAuthor(),bookdto.getCategoryCode(),bookdto.getAvailability()};
                  dtm.addRow(rowData);
              } 
              
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }  
    
    private void clearForm(){
        codetxt.setText("");
        titletxt.setText("");
        authortxt.setText("");
        categorytxt.setText("");
        availabilitytxt.setText("");
        
    }
    
    private void searchMouseClick() {
        try {
            String bookID= booktable.getValueAt(booktable.getSelectedRow(),0).toString();
            BookDto dto = BOOK_CONTROLLER.get(bookID);
            if(dto !=null){
                codetxt.setText(dto.getBookCode());
                titletxt.setText(dto.getBookTitle());
                authortxt.setText(dto.getAuthor());
                categorytxt.setText(dto.getCategoryCode());
                availabilitytxt.setText(Integer.toString(dto.getAvailability()));
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    
       
    }
}
