/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.lms.view;

import edu.ijse.lms.controller.BorrowingController;
import edu.ijse.lms.dto.BookDto;
import edu.ijse.lms.dto.BorrowingDto;
import edu.ijse.lms.dto.MemberDto;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class BorrowingView extends javax.swing.JFrame {
    private final BorrowingController BORROWING_CONTROLLER;
    private ArrayList<BorrowingDto> borrowingDtos = new ArrayList<>();

    /**
     * Creates new form BorrowingView
     */
    public BorrowingView() {
        initComponents();
        this.BORROWING_CONTROLLER=new BorrowingController();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        memberid = new javax.swing.JLabel();
        bookcode = new javax.swing.JLabel();
        membidtxt = new javax.swing.JTextField();
        bookcodetxt = new javax.swing.JTextField();
        membsearchbtn = new javax.swing.JButton();
        bookcodesearchbtn = new javax.swing.JButton();
        memberdata = new javax.swing.JLabel();
        bookdata = new javax.swing.JLabel();
        borrowing = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        borrowdatetxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        borrowingtbl = new javax.swing.JTable();
        borrowbtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        duedate = new javax.swing.JLabel();
        duedatetxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        memberid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        memberid.setText("Member ID");
        getContentPane().add(memberid, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        bookcode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bookcode.setText("Book Code");
        getContentPane().add(bookcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        membidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membidtxtActionPerformed(evt);
            }
        });
        getContentPane().add(membidtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 68, 125, 32));

        bookcodetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookcodetxtActionPerformed(evt);
            }
        });
        getContentPane().add(bookcodetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 120, 125, 32));

        membsearchbtn.setBackground(new java.awt.Color(255, 51, 204));
        membsearchbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        membsearchbtn.setText("Search");
        membsearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membsearchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(membsearchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 66, -1, -1));

        bookcodesearchbtn.setBackground(new java.awt.Color(255, 51, 204));
        bookcodesearchbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bookcodesearchbtn.setText("Search");
        bookcodesearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookcodesearchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(bookcodesearchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 118, -1, -1));

        memberdata.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(memberdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 68, 220, 32));
        getContentPane().add(bookdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 120, 220, 30));

        borrowing.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        borrowing.setText("Borrowing Books");
        getContentPane().add(borrowing, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        date.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        date.setText("Borrowing Date");
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 138, -1));

        borrowdatetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowdatetxtActionPerformed(evt);
            }
        });
        getContentPane().add(borrowdatetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 170, 125, 32));

        borrowingtbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        borrowingtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        borrowingtbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrowingtblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(borrowingtbl);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 277, 665, 141));

        borrowbtn.setBackground(new java.awt.Color(255, 51, 204));
        borrowbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        borrowbtn.setText("Place Borrow");
        borrowbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowbtnActionPerformed(evt);
            }
        });
        getContentPane().add(borrowbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 436, -1, -1));

        addbtn.setBackground(new java.awt.Color(255, 51, 204));
        addbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 220, -1, -1));

        duedate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        duedate.setText("Due Date");
        getContentPane().add(duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 99, -1));

        duedatetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duedatetxtActionPerformed(evt);
            }
        });
        getContentPane().add(duedatetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 222, 125, 32));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/lms/images/books new1111.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 740, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void membidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membidtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_membidtxtActionPerformed

    private void bookcodetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookcodetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookcodetxtActionPerformed

    private void borrowdatetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowdatetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrowdatetxtActionPerformed

    private void borrowingtblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowingtblMouseClicked
        // TODO add your handling code here:
        //        int i=itemtable.getSelectedRow();
        //        TableModel model=itemtable.getModel();
        //        itemtextfield.setText(model.getValueAt(i, 0).toString());
        //        desctextfield.setText(model.getValueAt(i, 1).toString());
        //        packtextfield.setText(model.getValueAt(i, 2).toString());
        //        unitpricefield.setText(model.getValueAt(i, 3).toString());
        //        qtyfield.setText(model.getValueAt(i, 4).toString());

    }//GEN-LAST:event_borrowingtblMouseClicked

    private void membsearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membsearchbtnActionPerformed
        searchMember();
        // TODO add your handling code here:
    }//GEN-LAST:event_membsearchbtnActionPerformed

    private void bookcodesearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookcodesearchbtnActionPerformed
        searchBook();
        // TODO add your handling code here:
    }//GEN-LAST:event_bookcodesearchbtnActionPerformed

    private void borrowbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowbtnActionPerformed
        // TODO add your handling code here:
        placeBorrowing();
    }//GEN-LAST:event_borrowbtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed

            addToTable();
            // TODO add your handling code here:
        
    }//GEN-LAST:event_addbtnActionPerformed

    private void duedatetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duedatetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duedatetxtActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BorrowingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BorrowingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BorrowingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BorrowingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new BorrowingView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JLabel bookcode;
    private javax.swing.JButton bookcodesearchbtn;
    private javax.swing.JTextField bookcodetxt;
    private javax.swing.JLabel bookdata;
    private javax.swing.JButton borrowbtn;
    private javax.swing.JTextField borrowdatetxt;
    private javax.swing.JLabel borrowing;
    private javax.swing.JTable borrowingtbl;
    private javax.swing.JLabel date;
    private javax.swing.JLabel duedate;
    private javax.swing.JTextField duedatetxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel memberdata;
    private javax.swing.JLabel memberid;
    private javax.swing.JTextField membidtxt;
    private javax.swing.JButton membsearchbtn;
    // End of variables declaration//GEN-END:variables

    private void searchMember() {
        try {
            String membID = membidtxt.getText();
            MemberDto dto = BORROWING_CONTROLLER.getMember(membID);
            memberdata.setText(dto.getMemberName() + " | " + dto.getAddress() + " | " + dto.getContact());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void searchBook() {
        try {
            String bookCode = bookcodetxt.getText();
            BookDto dto = BORROWING_CONTROLLER.getBook(bookCode);
            bookdata.setText(dto.getBookTitle() + " | " + dto.getAvailability());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } 
    }
    
    private void loadTable(){
        String columns[]={"MemberID","BookCode","BorrowingDate","DueDate"};
              DefaultTableModel dtm= new DefaultTableModel(columns,0){
                  @Override
                   public boolean isCellEditable(int row,int column){
                        return false;
                }
              };
              borrowingtbl.setModel(dtm);
    }
    
    private void addToTable(){
        try {
            BorrowingDto borrowingDto = new BorrowingDto();
        borrowingDto.setMemberID(membidtxt.getText());
        borrowingDto.setBookCode(bookcodetxt.getText());
        borrowingDto.setBorrowingDate(borrowdatetxt.getText());
        borrowingDto.setDueDate(duedatetxt.getText());
        SimpleDateFormat bdsdf = new SimpleDateFormat("dd/MM/yyyy");
        Date borrowingDate = bdsdf.parse(borrowdatetxt.getText());
        String borrowngDate = bdsdf.format(borrowingDate);
        borrowingDto.setBorrowingDate(borrowngDate);
//        
//        SimpleDateFormat ddsdf = new SimpleDateFormat("dd/MM/yyyy");
//        Date dueDate = ddsdf.parse(duedatetxt.getText());
//        String duedate = ddsdf.format(dueDate);
//        borrowingDto.setDueDate(duedate);
        borrowingDtos.add(borrowingDto);
        
        Object [] rowData = {borrowingDto.getMemberID(),borrowingDto.getBookCode(),borrowingDto.getBorrowingDate(),borrowingDto.getDueDate()};
        DefaultTableModel dtm=(DefaultTableModel) borrowingtbl.getModel();
        dtm.addRow(rowData);
        clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }

    
    private void placeBorrowing() {
        try {
             String resp=BORROWING_CONTROLLER.placeBorrowing(borrowingDtos);
             JOptionPane.showMessageDialog(this, resp);
             loadTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void clearForm(){
        membidtxt.setText("");
        bookcodetxt.setText("");
        borrowdatetxt.setText("");
        duedatetxt.setText("");
    }
    
    

}
