/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.lms.view;

/**
 *
 * @author ACER
 */
public class HomePageView extends javax.swing.JFrame {

    /**
     * Creates new form HomePageView
     */
    public HomePageView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        memberbtn = new javax.swing.JButton();
        bookbtn = new javax.swing.JButton();
        borrowbtn = new javax.swing.JButton();
        returnbtn = new javax.swing.JButton();
        bookcategory = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Library Management");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 490, -1));

        memberbtn.setBackground(new java.awt.Color(102, 255, 51));
        memberbtn.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        memberbtn.setText("Member");
        memberbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberbtnActionPerformed(evt);
            }
        });
        getContentPane().add(memberbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 187, 299, -1));

        bookbtn.setBackground(new java.awt.Color(255, 255, 51));
        bookbtn.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        bookbtn.setText("Book");
        bookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookbtnActionPerformed(evt);
            }
        });
        getContentPane().add(bookbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 187, 272, -1));

        borrowbtn.setBackground(new java.awt.Color(255, 51, 204));
        borrowbtn.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        borrowbtn.setText("Borrow Book");
        borrowbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowbtnActionPerformed(evt);
            }
        });
        getContentPane().add(borrowbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 464, 299, -1));

        returnbtn.setBackground(new java.awt.Color(51, 255, 255));
        returnbtn.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        returnbtn.setText("Return Book");
        returnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbtnActionPerformed(evt);
            }
        });
        getContentPane().add(returnbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 464, 272, -1));

        bookcategory.setBackground(new java.awt.Color(255, 102, 51));
        bookcategory.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        bookcategory.setText("Book Category");
        bookcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookcategoryActionPerformed(evt);
            }
        });
        getContentPane().add(bookcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 329, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/lms/images/books.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 900, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void memberbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberbtnActionPerformed
        memberFormLoad();
        // TODO add your handling code here:
    }//GEN-LAST:event_memberbtnActionPerformed

    private void bookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookbtnActionPerformed
        bookFormLoad();
        // TODO add your handling code here:
    }//GEN-LAST:event_bookbtnActionPerformed

    private void borrowbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowbtnActionPerformed
        borrowingLoad();
        // TODO add your handling code here:
    }//GEN-LAST:event_borrowbtnActionPerformed

    private void returnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbtnActionPerformed
        returnBookLoad();
        // TODO add your handling code here:
    }//GEN-LAST:event_returnbtnActionPerformed

    private void bookcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookcategoryActionPerformed
        bookCategoryLoad();
        // TODO add your handling code here:
    }//GEN-LAST:event_bookcategoryActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HomePageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HomePageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HomePageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HomePageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HomePageView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookbtn;
    private javax.swing.JButton bookcategory;
    private javax.swing.JButton borrowbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton memberbtn;
    private javax.swing.JButton returnbtn;
    // End of variables declaration//GEN-END:variables

    
    private void memberFormLoad() {
        new MemberView().setVisible(true);
    }

    private void bookFormLoad() {
         new BookView().setVisible(true);
    }

    private void borrowingLoad() {
         new BorrowingView().setVisible(true);
    }

    private void returnBookLoad() {
       new ReturnView().setVisible(true);
    }

    private void bookCategoryLoad() {
        new BookCategoryView().setVisible(true);
    }
    
}
