/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.lms.view;

import edu.ijse.lms.controller.MemberController;
import edu.ijse.lms.dto.MemberDto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class MemberView extends javax.swing.JFrame {
    private final MemberController MEMBER_CONTROLLER;
    private ArrayList<MemberDto>memberDtos=new ArrayList<>();

    /**
     * Creates new form MemberView
     */
    public MemberView() {
        initComponents();
        this.MEMBER_CONTROLLER=new MemberController();
        loadTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        membidtxt = new javax.swing.JTextField();
        nametxt = new javax.swing.JTextField();
        addresstxt = new javax.swing.JTextField();
        contacttxt = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        membertbl = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Member Form");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 19, 319, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Member ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 101, 133, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Member Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 150, 133, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Contact ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 150, 133, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 107, 133, -1));

        membidtxt.setToolTipText("");
        membidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membidtxtActionPerformed(evt);
            }
        });
        getContentPane().add(membidtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 101, 96, 31));

        nametxt.setToolTipText("");
        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });
        getContentPane().add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 150, 142, 31));

        addresstxt.setToolTipText("");
        addresstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addresstxtActionPerformed(evt);
            }
        });
        getContentPane().add(addresstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 101, 142, 31));

        contacttxt.setToolTipText("");
        contacttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contacttxtActionPerformed(evt);
            }
        });
        getContentPane().add(contacttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 150, 142, 31));

        savebtn.setBackground(new java.awt.Color(102, 255, 102));
        savebtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        savebtn.setText("Save");
        savebtn.setActionCommand("");
        savebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savebtnMouseClicked(evt);
            }
        });
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        getContentPane().add(savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 229, -1, -1));

        updatebtn.setBackground(new java.awt.Color(51, 255, 51));
        updatebtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updatebtn.setText("Update");
        updatebtn.setActionCommand("");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 229, -1, -1));

        deletebtn1.setBackground(new java.awt.Color(102, 255, 102));
        deletebtn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deletebtn1.setText("Delete");
        deletebtn1.setActionCommand("");
        deletebtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletebtn1MouseClicked(evt);
            }
        });
        deletebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(deletebtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 229, -1, -1));

        membertbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        membertbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                membertblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(membertbl);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 279, 756, 192));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/lms/images/bok new333.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void membidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membidtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_membidtxtActionPerformed

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    private void addresstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addresstxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addresstxtActionPerformed

    private void contacttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contacttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contacttxtActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        saveMember();
        // TODO add your handling code here:
    }//GEN-LAST:event_savebtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        updateMember();
        // TODO add your handling code here:
    }//GEN-LAST:event_updatebtnActionPerformed

    private void deletebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebtn1ActionPerformed

    private void savebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savebtnMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_savebtnMouseClicked

    private void deletebtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebtn1MouseClicked
        // TODO add your handling code here:
        deleteMember();
    }//GEN-LAST:event_deletebtn1MouseClicked

    private void membertblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membertblMouseClicked
        searchMouseClick();
        // TODO add your handling code here:
    }//GEN-LAST:event_membertblMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MemberView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MemberView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MemberView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MemberView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MemberView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addresstxt;
    private javax.swing.JTextField contacttxt;
    private javax.swing.JButton deletebtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable membertbl;
    private javax.swing.JTextField membidtxt;
    private javax.swing.JTextField nametxt;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables

    private void saveMember() {
        try {
            MemberDto membdto=new MemberDto(membidtxt.getText(),nametxt.getText(),addresstxt.getText(),Integer.parseInt(contacttxt.getText()));
            String resp = MEMBER_CONTROLLER.saveMember(membdto);
             JOptionPane.showMessageDialog(this, resp);
             loadTable();
             clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }
    
    private void deleteMember(){
        try {
            String membid=membidtxt.getText();
            String resp=MEMBER_CONTROLLER.deleteMember(membid);
            JOptionPane.showMessageDialog(this, resp);
            loadTable();
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    } 
    
      private void loadTable(){
          try {
              String columns[]={"MemberID","MemberName","Address","Contact"};
              DefaultTableModel dtm= new DefaultTableModel(columns,0){
                  @Override
                   public boolean isCellEditable(int row,int column){
                        return false;
                }
              };
              membertbl.setModel(dtm);
              ArrayList<MemberDto> memberDtos=MEMBER_CONTROLLER.getAll();
              for (MemberDto memberdto:memberDtos){
                  Object[] rowData={memberdto.getMemberID(),memberdto.getMemberName(),memberdto.getAddress(),memberdto.getContact()};
                  dtm.addRow(rowData);
              }
              
              
          } catch (Exception e) {
              JOptionPane.showMessageDialog(this, e.getMessage());
          }
      }

    private void updateMember() {
        try {
            MemberDto memberDto=new MemberDto(membidtxt.getText(),nametxt.getText(),addresstxt.getText(),Integer.parseInt(contacttxt.getText()));
            String resp = MEMBER_CONTROLLER.updateMember(memberDto);
            JOptionPane.showMessageDialog(this, resp);
            loadTable();
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    
    }
    
    private void clearForm(){
        membidtxt.setText("");
        nametxt.setText("");
        addresstxt.setText("");
        contacttxt.setText("");
    }

    private void searchMouseClick() {
        try {
           String membID = membertbl.getValueAt(membertbl.getSelectedRow(),0).toString();
           MemberDto dto = MEMBER_CONTROLLER.get(membID);
           if(dto!=null){
               membidtxt.setText(dto.getMemberID());
               nametxt.setText(dto.getMemberName());
               addresstxt.setText(dto.getAddress());
               contacttxt.setText(Integer.toString(dto.getContact()));
           }
          
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
       
    }
     

}
